services:

  # DB Manager (Gestisce la logica di accesso ai vari DB)
  db-manager:
    build: ./dbm
    environment:
      - DB_GATCHA_URL=mongodb://db-gatcha:27017  # URL di connessione al database di Gatcha
      - DB_USER_URL=mongodb://db-user:27017  # URL di connessione al database degli utenti

  # Gateway Service
  gateway:
    build: ./gateway
    ports:
      - "5001:5000"
    depends_on:
      - gatcha
      - user  # Commentato perché non necessario per Gacha
      - db-manager
    environment:
    - DBM_URL=http://db-manager:5000  # URL per connettersi al DBM


  # Gatcha service
  gatcha:
    build: ./gatcha
    depends_on:
      - db-manager  # Il servizio Gatcha dipende dal db-manager
    environment:
      - DBM_URL=http://db-manager:5000  # URL per connettersi a DBM

  # User Service
  user:
    build: ./user
    depends_on:
      - db-manager  # Aggiornato per dipendere da db-manager, non più dbm
    environment:
      - DBM_URL=http://db-manager:5000  # URL per connettersi a DBM

  # MongoDB for gatcha (Database per il servizio Gatcha)
  db-gatcha:
    image: mongo:latest
    ports:
      - "27017:27017"  # Porta esposta per il database
    volumes:
      - dbdata-gatcha:/data/db
      - ./mongo/seed-data:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: gatcha_db  # Nome del database per Gatcha
    command: mongod --quiet --logpath /dev/null  # Avvia MongoDB con log minimizzati

  # MongoDB for user (Database per il servizio User)
  db-user:
    image: mongo:latest
    ports:
      - "27018:27017"  # Host to container mapping
    volumes:
      - dbdata-user:/data/db
    environment:
      MONGO_INITDB_DATABASE: user_db  # Nome del database per gli utenti
    command: mongod --quiet --logpath /dev/null  # Avvia MongoDB con log minimizzati

volumes:
  dbdata-gatcha:
  dbdata-user:  # Volume per db-user
